config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :users
  resources :exchanges, only: [:index, :show] do
    collection do
      post :load_latest
    end
  end
  resource :reports, only: :show

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'exchanges#index'

end

app/models/currency.rb
class Currency < ActiveRecord::Base
  belongs_to :exchange

  validates :name, presence: true
  validates :converter, presence: true
  validates :converter, numericality: { only_integer: true }, allow_blank: true
  validates :code, presence: true
  validates :buy_price, presence: true
  validates :buy_price, numericality: true, allow_blank: true
  validates :sell_price, presence: true
  validates :sell_price, numericality: true, allow_blank: true
  validates :exchange_id, presence: true
end

app/models/exchange.rb
class Exchange < ActiveRecord::Base
  has_many :currencies, -> { order(:name) }

  validates :name, presence: true
  validates :quotation_date, presence: true
  validates :publication_date, presence: true
end

app/models/report.rb
class Report < ActiveRecord::Base
  def readonly?
    true
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  before_action :authenticate_user!

  add_breadcrumb "Tabele kursów", :exchanges_path

  def index
    @exchanges = Exchange.order(quotation_date: :desc).page params[:page]
  end

  def show
    @exchange = Exchange.find(params[:id])
    add_breadcrumb @exchange.name, exchange_path(@exchange)
  end

  def load_latest
    CurrenciesUpdater.perform_async
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_years
  before_action :load_codes
  before_action :report_types

  add_breadcrumb 'Raporty', :reports_path

  def show
    @report = Report.where(code: @selected_code, year: @selected_year).order(month: :asc)

    respond_to do |format|
      format.html
      format.js
      format.json { render json: generate_json }
    end
  end

  private

  def load_years
    @years = Report.pluck('DISTINCT year')
    @selected_year = params[:year] || @years.max
  end

  def load_codes
    @codes = Report.select('DISTINCT code, converter').map { |a| ["#{a.converter} #{a.code}", a.code] }
    @selected_code = params[:code] || @codes.first
  end

  def report_types
    @types = { 'Tabela' => :table, 'Wykres' => :chart }
    @selected_type = params[:type] || @types.first
  end

  def generate_json
    series = [{ key: 'Średnia cena kupna', values: [] }, { key: 'Średnia cena sprzedaży', values: [] },
              { key: 'Mediana ceny kupna', values: [] }, { key: 'Mediana ceny sprzedaży', values: [] }]

    @report.each do |r|
      series[0][:values].push(x: r.month, y: r.avg_buy_price)
      series[1][:values].push(x: r.month, y: r.avg_sell_price)
      series[2][:values].push(x: r.month, y: r.median_buy_price)
      series[3][:values].push(x: r.month, y: r.median_sell_price)
    end

    series.to_json
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def currency_code(currency)
    "#{currency.converter} #{currency.code}"
  end

  def active_class(controller)
    controller_name == controller && :active
  end
end

app/views/exchanges/index.html.haml
%p.pull-right
  = link_to 'Pobierz najnowszy kurs', load_latest_exchanges_path, class: 'btn btn-primary', id: 'load-latest'
.clearfix

- if @exchanges.present?
  %table.table.table-hover
    %thead
      %tr
        %th Nazwa tabeli
        %th Data notowania
        %th Data publikacji
    %tbody
      - @exchanges.each do |exchange|
        %tr.clickable{'data-url': exchange_path(exchange)}
          %td= exchange.name
          %td= exchange.quotation_date
          %td= exchange.publication_date

  %div.text-center
    = paginate @exchanges
- else
  .alert.alert-success Brak danych.

app/views/exchanges/load_latest.js.haml
:plain
  $('#load-latest').attr('disabled', true);
  $('#messages').html('<div class="alert alert-success alert-dismissible"> \
                        <button class="close" type="button" data-dismiss="alert" aria-label="Close"> \
                          <span aria-hidden="true"> &times</span> \
                        </button> \
                        Zadanie zostało zakolejkowane. \
                      </div');

app/views/exchanges/show.html.haml
%table.table
  %thead
    %tr
      %th Nazwa waluty
      %th Kod waluty
      %th Kurs kupna
      %th Kurs sprzedaży
  %tbody
    - @exchange.currencies.each do |currency|
      %tr
        %td= currency.name
        %td= currency_code currency
        %td= number_to_currency(currency.buy_price)
        %td= number_to_currency(currency.sell_price)

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_sym == :notice ? "success" : "danger"} alert-dismissible"}
      %button.close{type: 'button', 'data-dismiss': 'alert', 'aria-label': 'Close'}
        %span{'aria-hidden': true} &times
      = msg

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  %div.container
    %div.navbar-header
      %button.navbar-toggle.collapsed{ type: 'button', 'data-toggle': 'collapse', 'data-target': '#navbar',
       'aria-expanded': false, 'aria-controls': 'navbar' }
        %span.sr-only Toggle navigation
        %span.icon-bar
      = link_to 'Kursy NBP', '#', class: 'navbar-brand'
    %div#navbar.navbar-collapse.collapse
      %ul.nav.navbar-nav
        %li{class: active_class('exchanges')}
          = link_to 'Tabele kursów',exchanges_path
        %li{class: active_class('reports')}
          = link_to 'Raporty', reports_path
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          = link_to "#{current_user.try(:email) || 'Niezalogowany'} <span class=\"caret\"></span>".html_safe, '#',class: "dropdown-toggle", 'data-toggle': 'dropdown',
            role: 'button', 'aria-haspopup': true, 'aria-expanded': false
          %ul.dropdown-menu
            - if user_signed_in?
              %li= link_to 'Edytuj konto', edit_user_registration_path
              %li.divider{role: 'separator'}
              %li= link_to 'Wyloguj się', destroy_user_session_path, :method=>'delete'
            - else
              %li= link_to 'Zaloguj się', new_user_session_path
              %li= link_to 'Zarejestruj się', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
  %title NBP
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    .container
      .content
        .row
          .span12
            - if user_signed_in?
              %ol.breadcrumb
                = render_breadcrumbs :tag => :li, :separator => ""

            #messages
              = render 'layouts/messages'

            = yield

    .ajax-loader-modal

app/views/reports/_chart.html.haml
%p
  #chart{'data-url': reports_path(code: params[:code], year: params[:year], format: :json)}

:javascript
  function lineChart(containerId, data) {
    nv.addGraph(function() {
      var width = 1180,
          height = 500;

      var chart = nv.models.lineChart();

      chart.color(d3.scale.category10().range());
      chart.noData('Brak danych do wykresu');

      chart.tooltip.contentGenerator(function (obj) {
        return '<h3>' + obj['series'][0]['key'] + '</h3>' +
               '<p>' + obj['series'][0]['value'] + '</p>';
      });

      chart.xAxis
          .axisLabel("miesiące")
          .showMaxMin(false)
          .tickFormat(d3.format('d'));

      chart.yAxis
          .axisLabel("PLN")
          .showMaxMin(false)
          .tickFormat(d3.format(',.0f'));

      d3.select("#" + containerId).append('svg')
          .datum(data)
          .attr('width', width)
          .attr('height', height)
          .call(chart);

      nv.utils.windowResize(chart.update);

      return chart;
    });
  }

  d3.json($('#chart').data('url'), function(error, data) {
    if (error) {
      $('#chart').html("<div class=\"alert alert-danger\">Wystąpił błąd podczas generowania wykresu.</div>");
    } else {
      lineChart("chart", data);
    }
  });

app/views/reports/_table.html.haml
%table.table
  %thead
    %tr
      %th Miesiąc
      %th Średnia cena kupna
      %th Średnia cena sprzedaży
      %th Mediana ceny kupna
      %th Mediana ceny sprzedaży
  %tbody
    - @report.each do |report|
      %tr
        %td= report.month
        %td= report.avg_buy_price
        %td= report.avg_sell_price
        %td= report.median_buy_price
        %td= report.median_sell_price

app/views/reports/show.html.haml
- if @report.present?
  = form_tag('', method: :get, class: 'form-inline') do
    .form-group
      = label_tag 'code', 'Waluta:'
      = select_tag 'code', options_for_select(@codes, @selected_code), remote: true, class: 'form-control', id: 'reports-code'

    .form-group
      = label_tag 'type', 'Rodzaj raportu:'
      = select_tag 'type', options_for_select(@types, @selected_type), remote: true, class: 'form-control', id: 'reports-type'

    .form-group
      = label_tag 'year', 'Rok:'
      = select_tag 'year', options_for_select(@years, @selected_year), remote: true, class: 'form-control', id: 'reports-year'

  #show
    = render params[:type] || 'table'
- else
  .alert.alert-success Brak danych.

app/views/reports/show.js.haml
:plain
  $('#show').html('#{escape_javascript(render(partial: params[:type] || 'table'))}');